[package]
edition = "2021"
name = "yalem"
version = "0.1.0"

[dependencies]
gl = "*"
glutin = "*"
skia-safe = { version = "*", features = ["gl"] }

[dev-dependencies]
state = { version = "0.5", features = ["tls"] }
